version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - '3000:3000'
    restart: always
    environment:
      - POSTGRES_HOST="10.1.56.154"
      - POSTGRES_PORT=5432
      - POSTGRES_USER="admin"
      - POSTGRES_PASSWORD="abc"
      - POSTGRES_DB="user-service"
    depends_on:
      # - mongo
      - postgres
    volumes:
      - .:/app
      - /app/node_modules  
  # mongo:
  #   image: mongo
  #   ports:
  #     - '27017:27017'
  postgres:
    image: postgres
    ports: 
      - '5432:5432'
    environment :
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=abc
      - POSTGRES_DB=user-service
    
